version: '3'
services:
  nginx:
    build: './docker/nginx/'
    depends_on:
      - db
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
  php-fpm:
    build: './docker/php-fpm/'
    env_file:
      - .env
    volumes:
      - ./:/var/www/
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
