<?php return array (
  'october\\demo\\Plugin' => 'plugins\\october\\demo\\Plugin.php',
  'October\\Demo\\Components\\Todo' => 'plugins\\october\\demo\\components\\Todo.php',
  'backend\\Controllers\\index' => 'modules\\backend\\controllers\\index.php',
  'backend\\Controllers\\auth' => 'modules\\backend\\controllers\\auth.php',
  'cms\\Controllers\\index' => 'modules\\cms\\controllers\\index.php',
  'system\\Controllers\\settings' => 'modules\\system\\controllers\\settings.php',
  'system\\Controllers\\updates' => 'modules\\system\\controllers\\updates.php',
  'rainlab\\pages\\Plugin' => 'plugins\\rainlab\\pages\\Plugin.php',
  'RainLab\\Pages\\Components\\StaticPage' => 'plugins\\rainlab\\pages\\components\\StaticPage.php',
  'RainLab\\Pages\\Components\\StaticMenu' => 'plugins\\rainlab\\pages\\components\\StaticMenu.php',
  'RainLab\\Pages\\Components\\StaticBreadcrumbs' => 'plugins\\rainlab\\pages\\components\\StaticBreadcrumbs.php',
  'rainlab\\pages\\Controllers\\index' => 'plugins\\rainlab\\pages\\controllers\\index.php',
  'RainLab\\Pages\\Widgets\\PageList' => 'plugins\\rainlab\\pages\\widgets\\PageList.php',
  'RainLab\\Pages\\Widgets\\MenuList' => 'plugins\\rainlab\\pages\\widgets\\MenuList.php',
  'RainLab\\Pages\\Widgets\\SnippetList' => 'plugins\\rainlab\\pages\\widgets\\SnippetList.php',
  'RainLab\\Pages\\Classes\\PageList' => 'plugins\\rainlab\\pages\\classes\\PageList.php',
  'RainLab\\Pages\\Classes\\Page' => 'plugins\\rainlab\\pages\\classes\\Page.php',
  'RainLab\\Pages\\Classes\\Menu' => 'plugins\\rainlab\\pages\\classes\\Menu.php',
  'RainLab\\Pages\\Classes\\Content' => 'plugins\\rainlab\\pages\\classes\\Content.php',
  'RainLab\\Pages\\Classes\\SnippetManager' => 'plugins\\rainlab\\pages\\classes\\SnippetManager.php',
  'RainLab\\Pages\\Classes\\Controller' => 'plugins\\rainlab\\pages\\classes\\Controller.php',
  'RainLab\\Pages\\Classes\\Router' => 'plugins\\rainlab\\pages\\classes\\Router.php',
  'backend\\Controllers\\media' => 'modules\\backend\\controllers\\media.php',
  'cms\\Controllers\\themes' => 'modules\\cms\\controllers\\themes.php',
  'RainLab\\Pages\\Classes\\Snippet' => 'plugins\\rainlab\\pages\\classes\\Snippet.php',
);